ALTER TYPE "TinySyncStatus" ADD VALUE IF NOT EXISTS 'INVOICE_PENDING';
ALTER TYPE "TinySyncStatus" ADD VALUE IF NOT EXISTS 'INVOICE_FOUND';
ALTER TYPE "TinySyncStatus" ADD VALUE IF NOT EXISTS 'INVOICE_ISSUED';
ALTER TYPE "TinySyncStatus" ADD VALUE IF NOT EXISTS 'INVOICE_REJECTED';
ALTER TYPE "TinySyncStatus" ADD VALUE IF NOT EXISTS 'INVOICE_CANCELLED';

ALTER TABLE "pedidos" ADD COLUMN IF NOT EXISTS "nfTinyId" TEXT;
ALTER TABLE "pedidos" ADD COLUMN IF NOT EXISTS "nfSerie" TEXT;
ALTER TABLE "pedidos" ADD COLUMN IF NOT EXISTS "nfErro" TEXT;
