// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
config({ path: ".env.local" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations precisam de session mode (5432) — use DIRECT_URL local quando disponível.
    // Em Vercel, runtime usa DATABASE_URL (pgBouncer 6543); migrations rodam manualmente do dev.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
